server:
  port: 8081
spring:
  datasource:
    malldb:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.204:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
      username: root
      password: develop321
      initialSize: 5
      minIdle: 5
      maxIdle: 50
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      poolPreparedStatements: true
      testWhileIdle: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,logback
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0
    host: 192.168.10.204
    port: 6379
    password: null
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 100
        min-idle: 0
    timeout: 10000
jwt:
  rsa:
    publicKey: jwt/rsa/uat/yunyihenkeyJwt-uat.cer
    privateKey: jwt/rsa/uat/yunyihenkeyJwt-uat.pfx